### ISSUE TITLE
Blender crash when deleting vertices from imported model

### ISSUE THREAD

**Issue by maxwelllord** [ScreteMonge/Blender-Addons#2]
I'm not certain that this is a problem with the plugin itself, but I thought it was worth bringing to your attention

Download and open the following blend file

https://files.catbox.moe/up2vf7.blend

1. Select the model
2. Enter edit mode
3. Select one or more of the vertices of the bow the gnome is holding
4. Try to delete the selected vertices

This consistently crashes blender for me on both version 3.6 and 4.1

Crash log below

[gnome.crash.txt](https://github.com/user-attachments/files/15964435/gnome.crash.txt)

A workaround for this is to just separate the problem vertices and delete the object in object mode, however some vertices refuse to separate

**Comment by ScreteMonge** [comment]
Thanks for the report. I updated the import addon a couple weeks ago, are you using the latest version? If not, try uninstall and reinstall with the lastest package

**Comment by maxwelllord** [comment]
Seems to work fine on 1.1,thanks
